In [2]:
import numpy as np
world_alcohol = np.genfromtxt("world_alcohol.txt",delimiter=",",dtype=str)
print(type(world_alcohol))
print(world_alcohol)
print(help(np.genfromtxt))



<class 'numpy.ndarray'>
[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ...
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]
Help on function genfromtxt in module numpy.lib.npyio:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=None, replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes')
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discar

In [3]:
matrix = np.array([[1,2,3],[3,4,5]])
print(matrix)

[[1 2 3]
 [3 4 5]]


In [7]:
a = np.floor(10*np.random.random((3,4)))
print(a)
print("----------")
print(a.ravel())
print("----------")
a.shape = (6,2)
print(a)
print("----------")
print(a.T)


[[1. 4. 1. 8.]
 [9. 6. 4. 2.]
 [7. 7. 9. 6.]]
----------
[1. 4. 1. 8. 9. 6. 4. 2. 7. 7. 9. 6.]
----------
[[1. 4.]
 [1. 8.]
 [9. 6.]
 [4. 2.]
 [7. 7.]
 [9. 6.]]
----------
[[1. 1. 9. 4. 7. 9.]
 [4. 8. 6. 2. 7. 6.]]


In [8]:
a = np.arange(12)
b = a
print(b is a)
b.shape = (3,4)
print(a.shape)
print(id(a),id(b))


True
(3, 4)
1896217229232 1896217229232


In [9]:
#浅层复制地址不一样，但是公用一份数据，改变一个数值另一个也改变
c = a.view()
print(c is a)
c.shape = (2,6)
print(a.shape)
c[0,4] = 123
print(a)
print(id(a))
print(id(c))

False
(3, 4)
[[  0   1   2   3]
 [123   5   6   7]
 [  8   9  10  11]]
1896217229232
1896217229952


In [15]:
#
d  = a.copy()
print(d is a)
d[0,0] = 22
print(id(a))
print(id(d))

False
1896217229232
1896217228592


In [16]:
a = np.array([[4,3,5],[1,2,1]])
print(a)
print("-------")
b = np.sort(a,axis=1)
print(b)
a.sort(axis=1)
print("-------")
print(a)
a = np.array([4,3,1,2])
j = np.argsort(a)
print("---------")
print(j)
print("-------")
print(a[j])



[[4 3 5]
 [1 2 1]]
-------
[[3 4 5]
 [1 1 2]]
-------
[[3 4 5]
 [1 1 2]]
---------
[2 3 1 0]
-------
[1 2 3 4]


In [17]:
import pandas as pd

In [20]:
food_info = pd.read_csv("food_info.csv")
print(type(food_info))
print(food_info.dtypes)

<class 'pandas.core.frame.DataFrame'>
NDB_No               int64
Shrt_Desc           object
Water_(g)          float64
Energ_Kcal           int64
Protein_(g)        float64
Lipid_Tot_(g)      float64
Ash_(g)            float64
Carbohydrt_(g)     float64
Fiber_TD_(g)       float64
Sugar_Tot_(g)      float64
Calcium_(mg)       float64
Iron_(mg)          float64
Magnesium_(mg)     float64
Phosphorus_(mg)    float64
Potassium_(mg)     float64
Sodium_(mg)        float64
Zinc_(mg)          float64
Copper_(mg)        float64
Manganese_(mg)     float64
Selenium_(mcg)     float64
Vit_C_(mg)         float64
Thiamin_(mg)       float64
Riboflavin_(mg)    float64
Niacin_(mg)        float64
Vit_B6_(mg)        float64
Vit_B12_(mcg)      float64
Vit_A_IU           float64
Vit_A_RAE          float64
Vit_E_(mg)         float64
Vit_D_mcg          float64
Vit_D_IU           float64
Vit_K_(mcg)        float64
FA_Sat_(g)         float64
FA_Mono_(g)        float64
FA_Poly_(g)        float64
Cholestrl_(mg)   

In [23]:
# food_info.head(3)
food_info.tail(3)
print(food_info.columns)

Index(['NDB_No', 'Shrt_Desc', 'Water_(g)', 'Energ_Kcal', 'Protein_(g)',
       'Lipid_Tot_(g)', 'Ash_(g)', 'Carbohydrt_(g)', 'Fiber_TD_(g)',
       'Sugar_Tot_(g)', 'Calcium_(mg)', 'Iron_(mg)', 'Magnesium_(mg)',
       'Phosphorus_(mg)', 'Potassium_(mg)', 'Sodium_(mg)', 'Zinc_(mg)',
       'Copper_(mg)', 'Manganese_(mg)', 'Selenium_(mcg)', 'Vit_C_(mg)',
       'Thiamin_(mg)', 'Riboflavin_(mg)', 'Niacin_(mg)', 'Vit_B6_(mg)',
       'Vit_B12_(mcg)', 'Vit_A_IU', 'Vit_A_RAE', 'Vit_E_(mg)', 'Vit_D_mcg',
       'Vit_D_IU', 'Vit_K_(mcg)', 'FA_Sat_(g)', 'FA_Mono_(g)', 'FA_Poly_(g)',
       'Cholestrl_(mg)'],
      dtype='object')


In [24]:
print(food_info.loc[0])

NDB_No                         1001
Shrt_Desc          BUTTER WITH SALT
Water_(g)                     15.87
Energ_Kcal                      717
Protein_(g)                    0.85
Lipid_Tot_(g)                 81.11
Ash_(g)                        2.11
Carbohydrt_(g)                 0.06
Fiber_TD_(g)                      0
Sugar_Tot_(g)                  0.06
Calcium_(mg)                     24
Iron_(mg)                      0.02
Magnesium_(mg)                    2
Phosphorus_(mg)                  24
Potassium_(mg)                   24
Sodium_(mg)                     643
Zinc_(mg)                      0.09
Copper_(mg)                       0
Manganese_(mg)                    0
Selenium_(mcg)                    1
Vit_C_(mg)                        0
Thiamin_(mg)                  0.005
Riboflavin_(mg)               0.034
Niacin_(mg)                   0.042
Vit_B6_(mg)                   0.003
Vit_B12_(mcg)                  0.17
Vit_A_IU                       2499
Vit_A_RAE                   

In [26]:
ndb_col = food_info["NDB_No"]
print(ndb_col)

0        1001
1        1002
2        1003
3        1004
4        1005
5        1006
6        1007
7        1008
8        1009
9        1010
10       1011
11       1012
12       1013
13       1014
14       1015
15       1016
16       1017
17       1018
18       1019
19       1020
20       1021
21       1022
22       1023
23       1024
24       1025
25       1026
26       1027
27       1028
28       1029
29       1030
        ...  
8588    43544
8589    43546
8590    43550
8591    43566
8592    43570
8593    43572
8594    43585
8595    43589
8596    43595
8597    43597
8598    43598
8599    44005
8600    44018
8601    44048
8602    44055
8603    44061
8604    44074
8605    44110
8606    44158
8607    44203
8608    44258
8609    44259
8610    44260
8611    48052
8612    80200
8613    83110
8614    90240
8615    90480
8616    90560
8617    93600
Name: NDB_No, dtype: int64


In [30]:
col_names = food_info.columns.tolist()
print(col_names)
gram_columns = []
for c in col_names:
    if c.endswith("(g)"):
        gram_columns.append(c)

gram_df = food_info[gram_columns]
print(gram_df.head())

['NDB_No', 'Shrt_Desc', 'Water_(g)', 'Energ_Kcal', 'Protein_(g)', 'Lipid_Tot_(g)', 'Ash_(g)', 'Carbohydrt_(g)', 'Fiber_TD_(g)', 'Sugar_Tot_(g)', 'Calcium_(mg)', 'Iron_(mg)', 'Magnesium_(mg)', 'Phosphorus_(mg)', 'Potassium_(mg)', 'Sodium_(mg)', 'Zinc_(mg)', 'Copper_(mg)', 'Manganese_(mg)', 'Selenium_(mcg)', 'Vit_C_(mg)', 'Thiamin_(mg)', 'Riboflavin_(mg)', 'Niacin_(mg)', 'Vit_B6_(mg)', 'Vit_B12_(mcg)', 'Vit_A_IU', 'Vit_A_RAE', 'Vit_E_(mg)', 'Vit_D_mcg', 'Vit_D_IU', 'Vit_K_(mcg)', 'FA_Sat_(g)', 'FA_Mono_(g)', 'FA_Poly_(g)', 'Cholestrl_(mg)']
   Water_(g)  Protein_(g)  Lipid_Tot_(g)  Ash_(g)  Carbohydrt_(g)  \
0      15.87         0.85          81.11     2.11            0.06   
1      15.87         0.85          81.11     2.11            0.06   
2       0.24         0.28          99.48     0.00            0.00   
3      42.41        21.40          28.74     5.11            2.34   
4      41.11        23.24          29.68     3.18            2.79   

   Fiber_TD_(g)  Sugar_Tot_(g)  FA_Sat_(

In [31]:
print(food_info["Iron_(mg)"])
div_1000 = food_info["Iron_(mg)"] / 1000
print(div_1000)



0        0.02
1        0.16
2        0.00
3        0.31
4        0.43
5        0.50
6        0.33
7        0.64
8        0.16
9        0.21
10       0.76
11       0.07
12       0.16
13       0.15
14       0.13
15       0.14
16       0.38
17       0.44
18       0.65
19       0.23
20       0.52
21       0.24
22       0.17
23       0.13
24       0.72
25       0.44
26       0.20
27       0.22
28       0.23
29       0.41
        ...  
8588     9.00
8589     0.30
8590     0.10
8591     1.63
8592    34.82
8593     2.28
8594     0.17
8595     0.17
8596     4.86
8597     0.25
8598     0.23
8599     0.13
8600     0.11
8601     0.68
8602     7.83
8603     3.11
8604     0.30
8605     0.18
8606     0.80
8607     0.04
8608     3.87
8609     0.05
8610     0.38
8611     5.20
8612     1.50
8613     1.40
8614     0.58
8615     3.60
8616     3.50
8617     1.40
Name: Iron_(mg), dtype: float64
0       0.00002
1       0.00016
2       0.00000
3       0.00031
4       0.00043
5       0.00050
6       0.00033
7 


    food_info.sort_values("Sodium_(mg)",inplace=False)
    

In [32]:
food_info.sort_values("Sodium_(mg)",inplace=True)
print(food_info["Sodium_(mg)"])



760     0.0
758     0.0
405     0.0
761     0.0
2269    0.0
763     0.0
764     0.0
770     0.0
774     0.0
396     0.0
395     0.0
6827    0.0
394     0.0
393     0.0
391     0.0
390     0.0
787     0.0
788     0.0
2270    0.0
2231    0.0
407     0.0
748     0.0
409     0.0
747     0.0
702     0.0
703     0.0
704     0.0
705     0.0
706     0.0
707     0.0
       ... 
8153    NaN
8155    NaN
8156    NaN
8157    NaN
8158    NaN
8159    NaN
8160    NaN
8161    NaN
8163    NaN
8164    NaN
8165    NaN
8167    NaN
8169    NaN
8170    NaN
8172    NaN
8173    NaN
8174    NaN
8175    NaN
8176    NaN
8177    NaN
8178    NaN
8179    NaN
8180    NaN
8181    NaN
8183    NaN
8184    NaN
8185    NaN
8195    NaN
8251    NaN
8267    NaN
Name: Sodium_(mg), dtype: float64
